version: '2'

services:
  nginx:
    image: prooph/nginx:www
    ports:
      - 8080:80
      - 443:443
    links:
      - php:php
    volumes:
      - .:/var/www

  php:
    image: prooph/php:7.1-fpm
    volumes:
      - .:/var/www
    environment:
     #@TODO: move to app.env file
     # Set PROOPH_ENV=prod for production
      - PROOPH_ENV=dev
      - PDO_DSN=pgsql:host=postgres port=5432 dbname=event_machine
      - PDO_USER=postgres
      - PDO_PWD=
      - MONGO_SERVER=mongodb://mongodb:27017
      - MONGO_DB_NAME=event_machine

  aggregate_projection:
      image: prooph/php:7.1-cli
      volumes:
        - .:/app
      depends_on:
        - postgres
        - mongodb
      command: php /app/bin/aggregate_projection.php
      # Needed so that projection is automatically restarted when new events are registered in event machine
      # which are not yet known in the long-running projection process, see https://github.com/proophsoftware/event-machine-skeleton/issues/3
      restart: on-failure
      environment:
       #@TODO: move to app.env file
       # Set PROOPH_ENV=prod for production
        - PROOPH_ENV=dev
        - PDO_DSN=pgsql:host=postgres port=5432 dbname=event_machine
        - PDO_USER=postgres
        - PDO_PWD=
        - MONGO_SERVER=mongodb://mongodb:27017
        - MONGO_DB_NAME=event_machine

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 8081:15672
      - 15674:15674

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=event_machine
    volumes:
      - ./env/postgres/initdb.d:/docker-entrypoint-initdb.d:ro

  mongodb:
    image: mongo
    ports:
      - 27017:27017
